In [1]:
# Import our dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
print(application_df.shape)
application_df.head()

(34299, 12)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns,
application_df = application_df.drop(["EIN", "NAME", "SPECIAL_CONSIDERATIONS", "STATUS"],axis=1)
print(application_df.shape)
application_df.head()

(34299, 8)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1

In [3]:
# Determine the number of unique values in each column.
app_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
application_df[app_cat].nunique()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
INCOME_AMT           9
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_type_counts = application_df.APPLICATION_TYPE.value_counts()
app_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Determine which values to replace if counts are less than ...?
replace_application = list(app_type_counts[app_type_counts < 1000].index)

# Replace in dataframe
for app in replace_application:
    application_df.APPLICATION_TYPE = application_df.APPLICATION_TYPE.replace(app,"Other")
    
# Check to make sure binning was successful
application_df.APPLICATION_TYPE.value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
app_class_counts = application_df.CLASSIFICATION.value_counts()
app_class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1236        1
C2170        1
C1820        1
C1580        1
C3700        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# Determine which values to replace if counts are less than ..?
replace_class = list(app_class_counts[app_class_counts < 2000].index)

# Replace in dataframe
for cls in replace_class:
    application_df.CLASSIFICATION = application_df.CLASSIFICATION.replace(cls,"Other")
    
# Check to make sure binning was successful
application_df.CLASSIFICATION.value_counts()

C1000    17326
C2000     6074
Other     6062
C1200     4837
Name: CLASSIFICATION, dtype: int64

In [8]:
# Generate our categorical variable lists
app_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
application_df[app_cat].nunique()

APPLICATION_TYPE    6
AFFILIATION         6
CLASSIFICATION      4
USE_CASE            5
ORGANIZATION        4
INCOME_AMT          9
dtype: int64

In [9]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(application_df[app_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(app_cat)
encode_df.head()

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [10]:
# Merge one-hot encoded features and drop the originals
application_df = application_df.merge(encode_df,left_index=True, right_index=True)
application_df = application_df.drop(app_cat,1)
application_df.head()

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,108590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6692,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,142590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [11]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=28)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  30
hidden_nodes_layer2 = 20

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 30)                1080
_________________________________________________________________
dense_1 (Dense)              (None, 20)                620
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 21
=================================================================
Total params: 1,721
Trainable params: 1,721
Non-trainable params: 0
_________________________________________________________________

In [14]:
# Define the checkpoint path and filenames
os.makedirs("checkpoints_optimized_v3/",exist_ok=True)
checkpoint_path = "checkpoints_optimized_v3/weights.{epoch:02d}.hdf5"

In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Create a callback that saves the model's weights every 5 epochs
cp_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq=4000)

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])

Epoch 1/100
804/804 [==============================] - 1s 973us/step - loss: 0.5849 - accuracy: 0.7136
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5649 - accuracy: 0.7248
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5618 - accuracy: 0.7255
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7269
Epoch 5/100
759/804 [===========================>..] - ETA: 0s - loss: 0.5585 - accuracy: 0.7277
Epoch 00005: saving model to checkpoints_optimized_v3/weights.05.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5593 - accuracy: 0.7276
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5581 - accuracy: 0.7273
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5579 - accuracy: 0.7290
Epoch 8/100
804/804 [==============================] - 1s 932us/step - loss: 0.5569 - accuracy: 0.7292
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7304: 0s - loss: 0.5542
Epoch 10/100
756/804 [===========================>..] - ETA: 0s - loss: 0.5556 - accuracy: 0.7297
Epoch 00010: saving model to checkpoints_optimized_v3/weights.10.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5559 - accuracy: 0.7303
Epoch 11/100
804/804 [==============================] - 1s 920us/step - loss: 0.5554 - accuracy: 0.7293
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5553 - accuracy: 0.7303
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5548 - accuracy: 0.7297
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5540 - accuracy: 0.7306
Epoch 15/100
734/804 [==========================>...] - ETA: 0s - loss: 0.5524 - accuracy: 0.7317
Epoch 00015: saving model to checkpoints_optimized_v3/weights.15.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5539 - accuracy: 0.7305
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5540 - accuracy: 0.7307
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5535 - accuracy: 0.7310
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5531 - accuracy: 0.7300
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5532 - accuracy: 0.7311
Epoch 20/100
697/804 [=========================>....] - ETA: 0s - loss: 0.5534 - accuracy: 0.7313
Epoch 00020: saving model to checkpoints_optimized_v3/weights.20.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5534 - accuracy: 0.7310
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5528 - accuracy: 0.7306
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5527 - accuracy: 0.7323
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5525 - accuracy: 0.7312
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5522 - accuracy: 0.7317
Epoch 25/100
695/804 [========================>.....] - ETA: 0s - loss: 0.5537 - accuracy: 0.7313
Epoch 00025: saving model to checkpoints_optimized_v3/weights.25.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5523 - accuracy: 0.7313
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5519 - accuracy: 0.7307
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5518 - accuracy: 0.7310
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5520 - accuracy: 0.7316
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5517 - accuracy: 0.7323
Epoch 30/100
651/804 [=======================>......] - ETA: 0s - loss: 0.5504 - accuracy: 0.7326
Epoch 00030: saving model to checkpoints_optimized_v3/weights.30.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5518 - accuracy: 0.7317
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5515 - accuracy: 0.7321
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5515 - accuracy: 0.7322
Epoch 33/100
804/804 [==============================] - 1s 896us/step - loss: 0.5509 - accuracy: 0.7326
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5512 - accuracy: 0.7329
Epoch 35/100
627/804 [======================>.......] - ETA: 0s - loss: 0.5501 - accuracy: 0.7320
Epoch 00035: saving model to checkpoints_optimized_v3/weights.35.hdf5
804/804 [==============================] - 1s 900us/step - loss: 0.5510 - accuracy: 0.7336
Epoch 36/100
804/804 [==============================] - 1s 885us/step - loss: 0.5509 - accuracy: 0.7329
Epoch 37/100
804/804 [==============================] - 1s 980us/step - loss: 0.5506 - accuracy: 0.7334
Epoch 38/100
804/804 [==============================] - 1s 978us/step - loss: 0.5510 - accuracy: 0.7329
Epoch 39/100
804/804 [==============================] - 1s 924us/step - loss: 0.5506 - accuracy: 0.7334
Epoch 40/100
639/804 [======================>.......] - ETA: 0s - loss: 0.5502 - accuracy: 0.7338
Epoch 00040: saving model to checkpoints_optimized_v3/weights.40.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5505 - accuracy: 0.7332
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5506 - accuracy: 0.7333
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5503 - accuracy: 0.7329
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5506 - accuracy: 0.7330
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7324
Epoch 45/100
618/804 [======================>.......] - ETA: 0s - loss: 0.5507 - accuracy: 0.7316
Epoch 00045: saving model to checkpoints_optimized_v3/weights.45.hdf5
804/804 [==============================] - 1s 909us/step - loss: 0.5501 - accuracy: 0.7334
Epoch 46/100
804/804 [==============================] - 1s 909us/step - loss: 0.5502 - accuracy: 0.7336
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7329
Epoch 48/100
804/804 [==============================] - 1s 895us/step - loss: 0.5502 - accuracy: 0.7326
Epoch 49/100
804/804 [==============================] - 1s 894us/step - loss: 0.5496 - accuracy: 0.7341
Epoch 50/100
593/804 [=====================>........] - ETA: 0s - loss: 0.5474 - accuracy: 0.7358
Epoch 00050: saving model to checkpoints_optimized_v3/weights.50.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7339
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5495 - accuracy: 0.7341
Epoch 52/100
804/804 [==============================] - 1s 957us/step - loss: 0.5496 - accuracy: 0.7326
Epoch 53/100
804/804 [==============================] - 1s 988us/step - loss: 0.5491 - accuracy: 0.7339
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5495 - accuracy: 0.7336
Epoch 55/100
553/804 [===================>..........] - ETA: 0s - loss: 0.5478 - accuracy: 0.7349
Epoch 00055: saving model to checkpoints_optimized_v3/weights.55.hdf5
804/804 [==============================] - 1s 958us/step - loss: 0.5492 - accuracy: 0.7337
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5491 - accuracy: 0.7329
Epoch 57/100
804/804 [==============================] - 1s 965us/step - loss: 0.5492 - accuracy: 0.7332
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5491 - accuracy: 0.7333
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7341
Epoch 60/100
524/804 [==================>...........] - ETA: 0s - loss: 0.5511 - accuracy: 0.7322
Epoch 00060: saving model to checkpoints_optimized_v3/weights.60.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7339
Epoch 61/100
804/804 [==============================] - 1s 932us/step - loss: 0.5492 - accuracy: 0.7332
Epoch 62/100

804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7334
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7341
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7334
Epoch 65/100
541/804 [===================>..........] - ETA: 0s - loss: 0.5483 - accuracy: 0.7334
Epoch 00065: saving model to checkpoints_optimized_v3/weights.65.hdf5
804/804 [==============================] - 1s 964us/step - loss: 0.5484 - accuracy: 0.7334
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7332
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7342
Epoch 68/100
804/804 [==============================] - 1s 962us/step - loss: 0.5484 - accuracy: 0.7340
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7339
Epoch 70/100
493/804 [=================>............] - ETA: 0s - loss: 0.5464 - accuracy: 0.7353
Epoch 00070: saving model to checkpoints_optimized_v3/weights.70.hdf5
804/804 [==============================] - 1s 956us/step - loss: 0.5482 - accuracy: 0.7342
Epoch 71/100
804/804 [==============================] - 1s 931us/step - loss: 0.5483 - accuracy: 0.7347
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7337
Epoch 73/100
804/804 [==============================] - 1s 988us/step - loss: 0.5479 - accuracy: 0.7340
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7345
Epoch 75/100
504/804 [=================>............] - ETA: 0s - loss: 0.5479 - accuracy: 0.7347
Epoch 00075: saving model to checkpoints_optimized_v3/weights.75.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7347
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7346
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7337
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7346: 0s - loss: 0.5478 - accuracy: 0.73
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7344
Epoch 80/100
477/804 [================>.............] - ETA: 0s - loss: 0.5498 - accuracy: 0.7322
Epoch 00080: saving model to checkpoints_optimized_v3/weights.80.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7352
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7339
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7344
Epoch 83/100
804/804 [==============================] - 1s 913us/step - loss: 0.5477 - accuracy: 0.7347
Epoch 84/100
804/804 [==============================] - 1s 904us/step - loss: 0.5478 - accuracy: 0.7342
Epoch 85/100
447/804 [===============>..............] - ETA: 0s - loss: 0.5432 - accuracy: 0.7378
Epoch 00085: saving model to checkpoints_optimized_v3/weights.85.hdf5
804/804 [==============================] - 1s 913us/step - loss: 0.5476 - accuracy: 0.7355
Epoch 86/100
804/804 [==============================] - 1s 904us/step - loss: 0.5475 - accuracy: 0.7341
Epoch 87/100
804/804 [==============================] - 1s 905us/step - loss: 0.5474 - accuracy: 0.7345
Epoch 88/100
804/804 [==============================] - 1s 918us/step - loss: 0.5475 - accuracy: 0.7350
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7346: 0s - loss: 0.5465 - accuracy:
Epoch 90/100
397/804 [=============>................] - ETA: 0s - loss: 0.5503 - accuracy: 0.7310
Epoch 00090: saving model to checkpoints_optimized_v3/weights.90.hdf5
804/804 [==============================] - 1s 914us/step - loss: 0.5474 - accuracy: 0.7345
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7346
Epoch 92/100
804/804 [==============================] - 1s 962us/step - loss: 0.5473 - accuracy: 0.7352
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7350
Epoch 94/100
804/804 [==============================] - 1s 905us/step - loss: 0.5470 - accuracy: 0.7351
Epoch 95/100
389/804 [=============>................] - ETA: 0s - loss: 0.5433 - accuracy: 0.7349
Epoch 00095: saving model to checkpoints_optimized_v3/weights.95.hdf5
804/804 [==============================] - 1s 915us/step - loss: 0.5473 - accuracy: 0.7342
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7355
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7344
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7353
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7351
Epoch 100/100
380/804 [=============>................] - ETA: 0s - loss: 0.5482 - accuracy: 0.7332
Epoch 00100: saving model to checkpoints_optimized_v3/weights.100.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7345

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5608 - accuracy: 0.7308
Loss: 0.5607818365097046, Accuracy: 0.7308454513549805

In [19]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimaization.h5")